.\" name sect foot-centre foot-left  head-centre   origin  architecture
.TH xguess 1  "August 2000"  "GNU"  "User Commands" "GNU" ""
.SH NAME
xguess \- determine information about your X server
.SH SYNOPSIS
.BR "xguess" " [-s n] -xyzmnrvkhV"
.SH FLAGS
.PP
All flags except -s are exclusive.
.TP 4
\-h
prints a simple description of legal syntax and functions.
.TP 4
\-V
prints the version number of the program.
.TP 4
\-k
attempts to determine the type of keyboard attached to the X server
for the default display and screen.  Returns an identification string
in the format 
.I layout\-vendor\-model
.PP
.RS 4
Currently supported keyboard layouts
.IP lk201 8
Digital LK-201 used on DECStation 3100's and other older machines.
.IP lk401 8
Digital LK-401 used on DECStation 5000's and early Alpha's.
.IP pc84 8
IBM PC and PC/XT layout
.IP pc101 8
Standard PC layout (introduced with IBM PC/AT)
.IP type3 8
Sun Type 3 layout used for later Sun3 systems
.IP type4 8
Sun Type 4 layout used on early Sun4 systems
.IP type5 8
Sun Type 5 layout used on current Sun4 systems
.RE
.PP
.RS 4
Currently supported vendors
.IP dec 8
Digital Equipment Corporation.  Models include lk201, lk401, pcxal,
pc7xl.
.IP sun 8
Sun Microsystems. Models include type3, type4, type5 (with various
national variations).
.IP ncd 8
Network Computing Devices.  Models include n97, n101, n102, n107,
n108.
.IP ibm 8
International Business Machines.  Model 5168572M only.
.IP xfree86 8
XFree86, Incorporated.  A huge variety of models and national
variations.
.RE
.PP
.TP 4
\-m
returns the manufacturer string from the X server for the default
display and screen.
.TP 4
\-n
returns the number of screens (heads) attached to the specified
display.  See also -s.
.TP 4
\-r
returns the manufacturer's release number from the X server for the
default display and screen.  For X Consortium servers, this is the
release number of X11 (eg. 6000 == X11R6), but this does not apply to
all vendors.
.TP 4
\-s select a screen for a multi-head display.  By default, the -x -y
-z operations apply to screen 0.
.TP 4
\-v
returns protocol major and minor versions supported by the X server
for the default display and screen.  Note that this is 11.0 for
X11R[456].
.TP 4
\-x
returns the horizontal resolution of the default display and screen.
.TP 4
\-y
returns the vertical resolution of the default display and screen.
.TP 4
\-z
returns the maximum pixel depth of the default display and screen.
.SH DESCRIPTION
.PP
.B xguess
attempts to determine information about an X server.  It is designed
to be used in a
.I .xsession
file (see
.I xdm(1X)
) to enable display configuration on a platform-independent
basis.  Results are printed to
.I stdout
and can then be used in environment variables, etc.
.SH EXIT CODES
.PP
.TP 8
0
Returned a result with no errors detected.
.TP 8
1
Returned after detecting an error.  The result could be unreliable.
.SH EXAMPLE
.PP
An extract from a sample 
.I .xsession
file showing some uses of
.B xguess
.PP
.EX 4
#!/bin/csh

##  what sort of X Server am I using?
setenv XRES     "`xres -x`"
setenv YRES     "`xres -y`"
setenv XSERVER  "`xres -m`"
setenv XKEYBOARD "`xres -k`"

##  run appropriate XMODMAPRC
if ( -e $HOME/.xmodmaprc.$XKEYBOARD ) then
  xmodmap $HOME/.xmodmaprc.$XKEYBOARD
else
  xmodmap $HOME/.xmodmaprc.unknown
endif

##  biff next to TVTWM panner
##  (virtual WM: can't use geometry -300+0)
xbiff  -geometry +`expr $XRES - 300`+0 &
tvtwmrc -f $HOME/.tvtwmrc
.EE
.SH ENVIRONMENT
.PP
.TP 4
.B "DISPLAY"
To get the default host, display number, and screen.
.SH "SEE ALSO"
.PP
.I xdpyinfo(1X), 
.I xdm(1X),
.I xkbcomp(1X),
.br
.I The X Keyboard Extension: Library Specification
.SH AUTHOR
.PP
David Arnold, (davida@pobox.com)
.\" ***************************************************************
